language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
sudo: required
services:
 - docker
script: ./getcomponents.sh && docker build .
addons:
  ssh_known_hosts: antouk.bitbucket.org
