language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
sudo: required
services:
 - docker
env:
 - tag="dellelce/gpaw"
script: ./getcomponents.sh && docker build -t "${tag}" .
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push "${target}"
